# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rag.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\nragservice\"\x1c\n\nRagRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1b\n\x08RagReply\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\nRagService\x12;\n\x0bRagTemplate\x12\x16.ragservice.RagRequest\x1a\x14.ragservice.RagReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAGREQUEST']._serialized_start=25
  _globals['_RAGREQUEST']._serialized_end=53
  _globals['_RAGREPLY']._serialized_start=55
  _globals['_RAGREPLY']._serialized_end=82
  _globals['_RAGSERVICE']._serialized_start=84
  _globals['_RAGSERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
